import Head from 'next/head'
import Link from 'next/link'
import React, { useState } from 'react'
import { GoLocation } from 'react-icons/go'
import { FaEnvelopeSquare, FaPhoneAlt, FaMobile, FaFax, FaHome, FaPaperPlane } from 'react-icons/fa'
import { MdPersonPin } from 'react-icons/md'
import Image from 'next/image'
import { AnimatePresence, motion } from "framer-motion";

const Layout = ({title, children}) => {
  const [showModalMaps, setShowModalMaps] = useState(false);
  const [showModalPostuler, setShowModalPostuler] = useState(false);

  return (
    <>
      <Head>
        <title>{title ? title + ' - VL CLEANING SERVICES ' : 'VL CLEANING SERVICES'} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.div initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 1 }} className="flex flex-col justify-between min-h-screen">
        <header>
          <nav className="flex items-center justify-between h-16 px-4 text-white shadow-md bg-gradient-to-r from-blue-700 to-blue-500">
            <Link href="/">
              <a className="">
                <img src="/images/vl.jpeg" alt="VL CLEANING SERVICES" className="object-cover w-12 h-12 bg-white rounded-full hover:scale-125" />              
              </a>
            </Link>
            <div className="flex items-center justify-center space-x-2">
              <Link href="/">
                <a>
                  <FaHome className="text-2xl font-bold" />
                </a>
              </Link>
              <Link href="/rules">
                <a className="p-2">Qui sommes nous</a>
              </Link>
              <Link href="/contact">
                <a className="p-2">Contact</a>
              </Link>
              {/* <Link href="">
                <a className="p-2" onClick={() => setShowModalPostuler(true)}>Postuler</a>
              </Link> */}
            </div>
          </nav>
        </header>

        <main className="container px-4 m-auto mt-4">
          {children}
        </main>

        <p className="p-4 text-center border border-t-2 border-blue-600 focus-within:border-blue-700" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>Nous n'avons pas de poste vacant pour le moment, mais n'hésitez pas à nous envoyer votre CV sur l'adresse <i className="space-x-5 font-bold text-blue-800 animate-pulse">vlcleaningservice@hotmail.com</i></p>

        <footer className="grid grid-cols-1 gap-6 p-5 text-white shadow-inner md:grid-cols-4 lg:grid-cols-4 bg-gradient-to-r from-blue-700 to-blue-500">
            <div className="">
              <h4 className="mb-6 font-bold text-md">DS&VL sprl</h4>
              <h4>DS&VL sprl, entreprise de nettoyage vous proposant des prestations adaptées pour tous les secteurs d’activités et toutes les industries à Bruxelles, Flandre, Wallonie et partout en Belgique.</h4>
            </div>
            <div className="">
              <h4 className="mb-6 font-bold text-md"></h4>
              <h4></h4>
            </div>
            <div> 
              <h3 className="mb-5 text-2xl font-medium tracking-wider text-white">Contactez-nous !</h3>
              <div className="">
                <div className="flex space-x-2"> 
                  <h4 className="">TVA: BE0501 953 026</h4>  
                </div>
                <div className="flex space-x-2">
                  <MdPersonPin className="text-xl" />
                  <h4 className="">DURAKSAHIN Veli</h4>
                </div> 
                <div className="flex space-x-2">  
                  <FaPhoneAlt />
                  <h4 className="">+32(0) 487 56 68 25</h4>
                </div>
                 
                <div className="flex space-x-2">
                  <FaFax />
                  <h4 className="">+32(0) 2 387 06 66</h4>
                </div>      
                
                <div className="flex space-x-2">
                  <GoLocation onClick={() => setShowModalMaps(true)} className="text-xl text-white animate-pulse" />           
                  <h4 className="" onClick={() => setShowModalMaps(true)}>Rue Josaphat 332, 1030 Bruxelles Belgique</h4>
                </div>
                
                <div className="flex space-x-2">
                  <FaEnvelopeSquare className="text-xl" />
                  <h4 className="email animate-pulse" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>vlcleaningservice@hotmail.com</h4> 
                </div> 
              </div>
            </div>
            <div> 
              <div className="flex gap-2">
                <img src="/images/vl.jpeg" alt="VL CLEANING SERVICES" className="object-cover w-8 h-8 bg-white rounded-full hover:scale-125" />
                <h4 className="mb-5 text-xl font-medium tracking-wider text-white">VL CLEANING SERVICES</h4>
              </div>
              <div className="">
                <div className="flex space-x-2"> 
                  <Link href="/">
                    <a className="p-2">Accueil</a>
                  </Link>
                </div>
                <div className="flex space-x-2"> 
                  <Link href="/rules">
                    <a className="p-2">Qui sommes nous</a>
                  </Link>
                </div>
                <div className="flex space-x-2"> 
                  <Link href="/contact">
                    <a className="p-2">Contact</a>
                  </Link>
                </div>             
                
              </div>
            </div>
          
        </footer>
      </motion.div>

      {showModalMaps ? (
        <>
          <motion.div className="fixed inset-0 flex items-center justify-center overflow-x-hidden overflow-y-auto outline-none focus:outline-none">
            <div className="relative w-auto mx-auto my-6 max-w-7xl">
              {/*content*/}
              <div className="relative flex flex-col w-full bg-white border-0 rounded-lg shadow-lg outline-none focus:outline-none">
                <button className="float-right p-1 ml-auto text-3xl font-semibold leading-none text-blue-700 border-0 outline-none focus:outline-none"
                      onClick={() => setShowModalMaps(false)}
                    >
                    <span className="block w-6 h-6 text-blue-700">
                      ×
                    </span>
                  </button>
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2518.267254419673!2d4.374519351465912!3d50.86325187943398!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c3c36c2d4680a5%3A0xd9bbdc266629cde4!2sRue%20Josaphat%20332%2C%201030%20Schaerbeek!5e0!3m2!1sfr!2sbe!4v1654712298392!5m2!1sfr!2sbe" className="min-w-full rounded-lg" width="500" height="450" style={{border:0}} loading="lazy"></iframe>
              </div>
            </div>
          </motion.div>
        </>
      ) : null }

      {showModalPostuler ? (
        <>
          <motion.div className="fixed inset-0 flex items-center justify-center overflow-x-hidden overflow-y-auto outline-none focus:outline-none">
            <div className="relative w-auto mx-auto my-6 max-w-7xl">
              {/*content*/}
              <div className="relative flex flex-col w-full bg-white border-0 rounded-lg shadow-lg outline-none focus:outline-none">
                <button className="float-right p-1 ml-auto text-xl font-semibold leading-none border-0 outline-none focus:outline-none"
                      onClick={() => setShowModalPostuler(false)}
                    >
                    <span className="block w-6 h-6 text-blue-700">
                      ×
                    </span>
                    <h4 className="my-4 text-2xl font-medium tracking-wider text-center text-blue-700">ALL CLEANING SERVICES</h4>
                    <p className="" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>Nous n'avons pas de poste vacant pour le moment, mais n'hésitez pas à nous envoyer votre CV sur l'adresse <i className="space-x-3 text-blue-700 animate-pulse">vlcleaningservice@hotmail.com</i></p>
                    <p>Merci d'avance.</p>
                  </button>                 
              </div>
            </div>
          </motion.div>
        </>
      ) : null }

    </>
    
  )
}

export default Layout