const data = {
  products: [
    {
      name: 'Les vitrines de magasins',
      slug: 'Nettoyage de magasins, de grandes surfaces et de centres commerciaux',
      category: 'vitrines',
      image: '/images/vitrine-magasin.jpeg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Un magasin propre offre un sentiment de confort aux clients. S’ils se sentent bien dans votre magasin, ils feront plus vite confiance à vos produits. La propreté est donc un facteur essentiel pour la vente et la fidélisation de la clientèle. Votre façade ou votre vitrine a été taguée ? Nous enlevons aussi tout type de graffitis !',
    },
    {
      name: 'Les enseignes lumineuses',
      slug: 'Enseigne lumineuses',
      category: 'Shirts',
      image: '/images/enseigne.jpeg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'L’enseigne lumineuse c’est l’art de mettre en évidence votre activité correspondant le  mieux à l’environnement. Trouver l’équilibre et le juste milieu pour attirer l’attention et le regard curieux  afin d’éveiller l’intérê.',
    },
    {
      name: 'Les vérandas',
      slug: 'Nettoyage de Vérandas',
      category: 'Shirts',
      image: '/images/nettoyageverandas.jpeg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Nettoyer une véranda est une opération délicate qui peut vite devenir périlleuse. Nos équipes de laveurs de vitres sont spécialement formés pour travailler en hauteur. De plus, elles disposent de tout l’équipement nécessaire pour effectuer leurs missions en toute sécurité.Une fois les vitres nettoyées, vous profitez à nouveau pleinement de votre véranda. Faites entrer la lumière dans votre maison.',
    },
    {
      name: 'Les vélux',
      slug: 'Nettoyage de fenêtres de toit',
      category: 'Pants',
      image: '/images/velux.png',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "En effet, en plus d'être une société principalement active dans le lavage de vitres et le réseau de panneaux solaires, nous netyons également les fenêtres de toit.",
    },
    {
      name: 'Les hauteurs',
      slug: 'Lavage de vitres à la hauteur',
      category: 'Pants',
      image: '/images/hauteur.jpeg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: "Nos laveurs de vitres sont expérimentés à diverses techniques de nettoyage vitres. La matériel utilisé est choisi en adéquation avec la surface à nettoyer pour obtenir un résultat optimal dans les meilleures conditions de sécurité. Certains n’hésitent pas à prendre de la hauteur pour nettoyer les surfaces vitrées plus difficiles d’accès.",
    }
  ],
};

export default data;
