import React, { Fragment, useState } from 'react'
import { GoLocation } from 'react-icons/go'
import { FaEnvelopeSquare, FaPhoneAlt, FaMobile, FaFax, FaHome, FaPaperPlane } from 'react-icons/fa'
import { MdPersonPin } from 'react-icons/md'
import { Popover, Transition } from '@headlessui/react'
import { Bars3Icon, XMarkIcon} from '@heroicons/react/24/outline'
//import { ChevronDownIcon } from '@heroicons/react/20/solid'
import Link from 'next/link'
import Head from 'next/head'
import { AnimatePresence, motion } from "framer-motion";

const Layout = ({title, children}) => {
  const [showModalMaps, setShowModalMaps] = useState(false);
  const [showModalPostuler, setShowModalPostuler] = useState(false);

  return (
    <>
      <Head>
        <title>{title ? title + ' - ALL CLEANING SERVICES ' : 'ALL CLEANING SERVICES'} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <motion.div initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 1 }} className="flex flex-col justify-between min-h-screen">
        <header>
          <Popover className="relative bg-white">
            <div className="px-4 mx-auto max-w-7xl sm:px-6">
              <div className="flex items-center justify-between py-6 border-b-2 border-blue-100 md:justify-start md:space-x-10">
                <div className="flex justify-start lg:w-0 lg:flex-1">
                  <Link href="/">
                    <a>
                      <span className="sr-only">ALL CLEANING SERVICES</span>
                      <img
                        className="w-auto h-8 sm:h-10"
                        src="/images/Services.png"
                        alt=""
                      />
                    </a>
                  </Link>
                </div>
                <div className="-my-2 -mr-2 md:hidden">
                  <Popover.Button className="inline-flex items-center justify-center p-2 text-blue-400 bg-white rounded-md hover:bg-blue-100 hover:text-blue-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                    <span className="sr-only">Ouvrir menu</span>
                    <Bars3Icon className="w-6 h-6" aria-hidden="true" />
                  </Popover.Button>
                </div>
                
                <div className="items-center justify-end hidden md:flex md:flex-1 lg:w-0">
                  <Link href="/">
                    <a className="text-base font-medium text-blue-500 whitespace-nowrap hover:text-blue-900">
                      <FaHome className="text-2xl font-bold" />
                    </a>
                  </Link>
                  <Link href="/rules">
                    <a className="px-4 py-2 ml-8 text-base font-medium text-blue-500 whitespace-nowrap hover:text-blue-900">
                    Qui sommes nous
                    </a>
                  </Link>
                  <Link href="/contact">
                    <a className="px-4 py-2 ml-4 text-base font-medium text-blue-500 whitespace-nowrap hover:text-blue-900">
                      Contact
                    </a>
                  </Link>
                  {/* <a
                    href="#"
                    className="inline-flex items-center justify-center px-4 py-2 ml-8 text-base font-medium text-white bg-indigo-600 border border-transparent rounded-md shadow-sm whitespace-nowrap hover:bg-indigo-700"
                  >
                    Qui sommes nous
                  </a> */}
                </div>
              </div>
            </div>

            <Transition
              as={Fragment}
              enter="duration-200 ease-out"
              enterFrom="opacity-0 scale-95"
              enterTo="opacity-100 scale-100"
              leave="duration-100 ease-in"
              leaveFrom="opacity-100 scale-100"
              leaveTo="opacity-0 scale-95"
            >
              <Popover.Panel focus className="absolute inset-x-0 top-0 p-2 transition origin-top-right transform md:hidden">
                <div className="bg-white divide-y-2 rounded-lg shadow-lg divide-blue-50 ring-1 ring-black ring-opacity-5">
                  <div className="px-5 pt-5 pb-6">
                    <div className="flex items-center justify-between">
                      <div>
                        <img
                          className="w-auto h-8"
                          src="/images/Services.png"
                          alt="ALL CLEANING SERVICES"
                        />
                      </div>
                      <div className="-mr-2">
                        <Popover.Button className="inline-flex items-center justify-center p-2 text-blue-400 bg-white rounded-md hover:bg-blue-100 hover:text-blue-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500">
                          <span className="sr-only">Close menu</span>
                          <XMarkIcon className="w-6 h-6" aria-hidden="true" />
                        </Popover.Button>
                      </div>
                    </div>
                  </div>
                  <div className="px-5 py-6 space-y-6">
                    <div>
                      <p className="mt-6 text-base font-medium text-center text-blue-500">
                        <Link href="/">
                          <a className="text-blue-600 hover:text-blue-500">
                            Accueil
                          </a>
                        </Link>
                      </p>
                      <p className="mt-6 text-base font-medium text-center text-blue-500">
                        <Link href="/rules">
                          <a className="text-blue-600 hover:text-blue-500">
                            Qui sommes nous
                          </a>
                        </Link>
                      </p>
                      <p className="mt-6 text-base font-medium text-center text-blue-500">
                        <Link href="/contact">
                          <a className="text-blue-600 hover:text-blue-500">
                            Contact
                          </a>
                        </Link>
                      </p>
                    </div>
                  </div>
                </div>
              </Popover.Panel>
            </Transition>
          </Popover>
        </header>
      
        <main className="container px-4 m-auto mt-4">
          {children}
        </main>

        <p className="p-4 text-center border border-t-2 border-blue-600 focus-within:border-blue-700" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>Nous n'avons pas de poste vacant pour le moment, mais n'hésitez pas à nous envoyer votre CV sur l'adresse <i className="space-x-5 font-bold text-blue-800 animate-pulse">vlcleaningservice@hotmail.com</i></p>

        <footer className="grid grid-cols-1 gap-6 p-5 text-white shadow-inner md:grid-cols-4 lg:grid-cols-4 bg-gradient-to-r from-blue-700 to-blue-500">
            <div className="">
              <h4 className="mb-6 font-bold text-md">DS&VL sprl</h4>
              <h4>DS&VL sprl, entreprise de nettoyage vous proposant des prestations adaptées pour tous les secteurs d’activités et toutes les industries à Bruxelles, Flandre, Wallonie et partout en Belgique.</h4>
            </div>
            <div className="">
              <h4 className="mb-6 font-bold text-md"></h4>
              <h4></h4>
            </div>
            <div> 
              <h3 className="mb-5 text-2xl font-medium tracking-wider text-white">Contactez-nous !</h3>
              <div className="">
                <div className="flex space-x-2"> 
                  <h4 className="">TVA: BE0501 953 026</h4>  
                </div>
                <div className="flex space-x-2">
                  <MdPersonPin className="text-xl" />
                  <h4 className="">DURAKSAHIN Veli</h4>
                </div> 
                <div className="flex space-x-2">  
                  <FaPhoneAlt />
                  <h4 className="">+32(0) 487 56 68 25</h4>
                </div>
                 
                <div className="flex space-x-2">
                  <FaFax />
                  <h4 className="">+32(0) 2 387 06 66</h4>
                </div>      
                
                <div className="flex space-x-2">
                  <GoLocation onClick={() => setShowModalMaps(true)} className="text-xl text-white animate-pulse" />           
                  <h4 className="" onClick={() => setShowModalMaps(true)}>Rue Josaphat 332, 1030 Bruxelles Belgique</h4>
                </div>
                
                <div className="flex space-x-2">
                  <FaEnvelopeSquare className="text-xl" />
                  <h4 className="email animate-pulse" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>vlcleaningservice@hotmail.com</h4> 
                </div> 
              </div>
            </div>
            <div> 
              <h4 className="mb-5 text-xl font-medium tracking-wider text-white">ALL CLEANING SERVICES</h4>
              <div className="">
                <div className="flex space-x-2"> 
                  <Link href="/">
                    <a className="p-2">Accueil</a>
                  </Link>
                </div>
                <div className="flex space-x-2"> 
                  <Link href="/rules">
                    <a className="p-2">Qui sommes nous</a>
                  </Link>
                </div>
                <div className="flex space-x-2"> 
                  <Link href="/contact">
                    <a className="p-2">Contact</a>
                  </Link>
                </div>             
                
              </div>
            </div>
          
        </footer>
      </motion.div>

        {showModalMaps ? (
        <>
          <motion.div className="fixed inset-0 flex items-center justify-center overflow-x-hidden overflow-y-auto outline-none focus:outline-none">
            <div className="relative w-auto mx-auto my-6 max-w-7xl">
              {/*content*/}
              <div className="relative flex flex-col w-full bg-white border-0 rounded-lg shadow-lg outline-none focus:outline-none">
                <button className="float-right p-1 ml-auto text-3xl font-semibold leading-none text-blue-700 border-0 outline-none focus:outline-none"
                      onClick={() => setShowModalMaps(false)}
                    >
                    <span className="block w-6 h-6 text-blue-700">
                      ×
                    </span>
                  </button>
                  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2518.267254419673!2d4.374519351465912!3d50.86325187943398!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47c3c36c2d4680a5%3A0xd9bbdc266629cde4!2sRue%20Josaphat%20332%2C%201030%20Schaerbeek!5e0!3m2!1sfr!2sbe!4v1654712298392!5m2!1sfr!2sbe" className="min-w-full rounded-lg" width="500" height="450" style={{border:0}} loading="lazy"></iframe>
              </div>
            </div>
          </motion.div>
        </>
      ) : null }

      {showModalPostuler ? (
        <>
          <motion.div className="fixed inset-0 flex items-center justify-center overflow-x-hidden overflow-y-auto outline-none focus:outline-none">
            <div className="relative w-auto mx-auto my-6 max-w-7xl">
              {/*content*/}
              <div className="relative flex flex-col w-full bg-white border-0 rounded-lg shadow-lg outline-none focus:outline-none">
                <button className="float-right p-1 ml-auto text-xl font-semibold leading-none border-0 outline-none focus:outline-none"
                      onClick={() => setShowModalPostuler(false)}
                    >
                    <span className="block w-6 h-6 text-blue-700">
                      ×
                    </span>
                    <h4 className="my-4 text-2xl font-medium tracking-wider text-center text-blue-700">ALL CLEANING SERVICES</h4>
                    <p className="" onClick={() => window.open('mailto:vlcleaningservice@hotmail.com')}>Nous n'avons pas de poste vacant pour le moment, mais n'hésitez pas à nous envoyer votre CV sur l'adresse <i className="space-x-3 text-blue-700 animate-pulse">vlcleaningservice@hotmail.com</i></p>
                    <p>Merci d'avance.</p>
                  </button>                 
              </div>
            </div>
          </motion.div>
        </>
      ) : null }

    </>
  )
}

export default Layout